### ISSUE TITLE
Migrate From Travis CI to Github Actions

### ISSUE THREAD

**Issue by jasoncorum** [WGBH-MLA/AAPB2#2333]
Since Travis CI moved to a pay-model, and we've exhausted our free credits, we need a new CI solution. After some preliminary investigating and implementing on AAPB, Github Actions seems like our best bet.

The AAPB2 repo has a PR #2332 which uses Github Actions for CI. It sets up the machine, runs RSpec, and Rubocop. This can be used as a starting place for our other repositories. 

***DONE WHEN***

The following repositories use Github Actions for CI:

- [ ] ams - https://github.com/WGBH-MLA/ams
- [ ] mlavalon - https://github.com/WGBH-MLA/mlavalon
- [ ] openvault3 - https://github.com/WGBH-MLA/openvault3

_Not included: stock-sales-2, bostonlocaltv, transcript-editor as these sites are out of date or the testing infrastructure isn't fully in place_
