### ISSUE TITLE
IIIF Presentation API Endpoint

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/AAPB2#2752]
### Summary

In partnership AVP and Brumfield Labs, UT-Austin would like to use their audio annotation tool AVAnnotate on AAPB streaming content. 

To do this most efficiently on their end, they have requested that we add a IIIF Presentation API endpoint to AAPB code.

### Alternatives

Brumfield labs folks offered to write additional, AAPB-specific code into AudiAnnotate to read AAPB's PBCore metadata files and convert them into IIIF manifests, but this would be more labor intensive and would have minimal benefits to AAPB long-term.

### Additional context

See AVAnnotate AAPB experiment thread email - February 7-April 16

### Done when
AAPB has a route that responds with a valid IIIF manifest for records having playable media
```[tasklist]
### Tasks
- [x] Convert duration from hhh:mm:ss.mmm (string) to seconds (float) with milisecond precision.
- [x] remove unnecessary/redundant property from `items[n].label`
- [x] add specs ~with validation against a proper validator~ testing basic functionality of the endpoint
```

**Comment by ekemeyer** [comment]
Met with Sara and Ben on June 27th - ran IIIF url through validator. Main issue was with duration value.

Deadline for July 24th to wrap up revisions and email Sara/Ben.
Goal to have something to present first week of August.
